apiVersion: apps/v1 # change here
kind: ReplicaSet
metadata:
  name: hello-rs
spec:
  replicas: 2
  selector:
    matchLabels: # change here
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
        - image: haihoanguci/hello-k8s
          name: hello-kube
          ports:
            - containerPort: 3000
